package com.mycompany.projetocarro;
//Matheus Duarte 2417820
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Matheuws Duarte
 */
public class cadNovo extends javax.swing.JFrame {
    
    
    private Novo n = new Novo();
    private static cadNovo cadastroNovo;
    
    
    private cadNovo() {
        initComponents();
    }
    
    
    public static cadNovo getcadNovo(){
        
        if(cadastroNovo == null){
            
            cadastroNovo = new cadNovo();
            
        }
        
        return cadastroNovo;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblNserie = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblNparcelas = new javax.swing.JLabel();
        lblvalorEntrada = new javax.swing.JLabel();
        txtAnocadNovo = new javax.swing.JTextField();
        txtSeriecadNovo = new javax.swing.JTextField();
        txtValorcadNovo = new javax.swing.JTextField();
        txtModelocadNovo = new javax.swing.JTextField();
        txtMarcacadNovo = new javax.swing.JTextField();
        txtParcelascadNovo = new javax.swing.JTextField();
        txtEntradacadNovo = new javax.swing.JTextField();
        btnCadastrarcadNovo = new javax.swing.JButton();
        btnConsultarcadNovo = new javax.swing.JButton();
        btnAlterarcadNovo = new javax.swing.JButton();
        btnRemovercadNovo = new javax.swing.JButton();
        btnLimparcadNovo = new javax.swing.JButton();
        btnSaircadNovo = new javax.swing.JButton();
        ScrollPaneNovo = new javax.swing.JScrollPane();
        tabNovo = new javax.swing.JTable();
        comboNovo = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setText("CADASTRO CARRO NOVO");

        lblAno.setText("Ano");

        lblNserie.setText("Número de Serie");

        lblValor.setText("Valor");

        lblModelo.setText("Modelo");

        lblMarca.setText("Marca");

        lblNparcelas.setText("Número de Parcelas");

        lblvalorEntrada.setText("Valor da Entrada");

        txtValorcadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorcadNovoActionPerformed(evt);
            }
        });

        txtModelocadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelocadNovoActionPerformed(evt);
            }
        });

        txtMarcacadNovo.setToolTipText("");
        txtMarcacadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcacadNovoActionPerformed(evt);
            }
        });

        txtParcelascadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParcelascadNovoActionPerformed(evt);
            }
        });

        txtEntradacadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradacadNovoActionPerformed(evt);
            }
        });

        btnCadastrarcadNovo.setText("Cadastrar");
        btnCadastrarcadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarcadNovoActionPerformed(evt);
            }
        });

        btnConsultarcadNovo.setText("Consultar");
        btnConsultarcadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarcadNovoActionPerformed(evt);
            }
        });

        btnAlterarcadNovo.setText("Alterar");
        btnAlterarcadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarcadNovoActionPerformed(evt);
            }
        });

        btnRemovercadNovo.setText("Remover");
        btnRemovercadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovercadNovoActionPerformed(evt);
            }
        });

        btnLimparcadNovo.setText("Limpar");
        btnLimparcadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparcadNovoActionPerformed(evt);
            }
        });

        btnSaircadNovo.setText("Sair");
        btnSaircadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaircadNovoActionPerformed(evt);
            }
        });

        tabNovo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "N° Parcelas", "Valor Entrada"
            }
        ));
        tabNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNovoMouseClicked(evt);
            }
        });
        ScrollPaneNovo.setViewportView(tabNovo);

        comboNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrarcadNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarcadNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarcadNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemovercadNovo))
                    .addComponent(ScrollPaneNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtModelocadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtMarcacadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblModelo)
                        .addGap(189, 189, 189)
                        .addComponent(lblMarca))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAnocadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNserie)
                                    .addComponent(txtSeriecadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor)
                            .addComponent(txtValorcadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtParcelascadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNparcelas))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblvalorEntrada)
                            .addComponent(txtEntradacadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(244, 244, 244)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLimparcadNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaircadNovo)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(lblNserie)
                    .addComponent(lblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnocadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSeriecadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorcadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelocadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcacadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNparcelas)
                    .addComponent(lblvalorEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtParcelascadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntradacadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarcadNovo)
                    .addComponent(btnConsultarcadNovo)
                    .addComponent(btnAlterarcadNovo)
                    .addComponent(btnRemovercadNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPaneNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparcadNovo)
                    .addComponent(btnSaircadNovo))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorcadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorcadNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorcadNovoActionPerformed

    private void txtModelocadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelocadNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelocadNovoActionPerformed

    private void txtMarcacadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcacadNovoActionPerformed
        // TODO add yohandling code here:
    }//GEN-LAST:event_txtMarcacadNovoActionPerformed

    private void txtParcelascadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParcelascadNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParcelascadNovoActionPerformed

    private void txtEntradacadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradacadNovoActionPerformed

    }//GEN-LAST:event_txtEntradacadNovoActionPerformed

    private void btnSaircadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaircadNovoActionPerformed
        sair();
    }//GEN-LAST:event_btnSaircadNovoActionPerformed

    private void btnLimparcadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparcadNovoActionPerformed
       limpar();
    }//GEN-LAST:event_btnLimparcadNovoActionPerformed

    private void btnCadastrarcadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarcadNovoActionPerformed
       cadastrar();
       listTab();
       carregarCombNovo();
    }//GEN-LAST:event_btnCadastrarcadNovoActionPerformed

    private void btnConsultarcadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarcadNovoActionPerformed
       consNovoSerie();
    }//GEN-LAST:event_btnConsultarcadNovoActionPerformed

    private void btnAlterarcadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarcadNovoActionPerformed
        altNovoSerie();
        listTab();
        carregarCombNovo();    
    }//GEN-LAST:event_btnAlterarcadNovoActionPerformed

    private void btnRemovercadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovercadNovoActionPerformed
        excNovoSerie();
        listTab();
        carregarCombNovo();  
    }//GEN-LAST:event_btnRemovercadNovoActionPerformed

    private void comboNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNovoActionPerformed
        selectComboNovo();
    }//GEN-LAST:event_comboNovoActionPerformed

    private void tabNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNovoMouseClicked
       selectTab();
    }//GEN-LAST:event_tabNovoMouseClicked

 
     public void cadastrar(){
        n = new Novo();
        
        try{    
            n.setAno(Integer.parseInt(txtAnocadNovo.getText()));
            n.setSerie(Integer.parseInt(txtSeriecadNovo.getText()));
            n.setValor(Double.parseDouble(txtValorcadNovo.getText()));
            n.setModelo(txtModelocadNovo.getText());
            n.setMarca(txtMarcacadNovo.getText());
            n.setNumeroParcelas(Integer.parseInt(txtParcelascadNovo.getText()));
            n.setValorEntrada(Double.parseDouble(txtEntradacadNovo.getText()));
        
        n = GerNovo.getGerNovo().cadNovo(n);
        
        if(n != null){
            JOptionPane.showMessageDialog(
                    null,
                    "Carro novo cadastrado com sucesso",
                    "Cadastro Carro Novo",
                    JOptionPane.PLAIN_MESSAGE
                );
            limpar();
        }
        else{
                    JOptionPane.showMessageDialog(
                    null,
                    "Já existe um Carro com esse número de Serie.",
                    "Cadastro Carro Novo",
                    JOptionPane.ERROR_MESSAGE
                );
        }
    }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                    null,
                    "O número de serie deve ser um int",
                    "Erro de preenchimento",
                    JOptionPane.ERROR_MESSAGE
                );
         }   
    }
     
     public void altNovoSerie(){
        n = new Novo();
        n.setSerie(Integer.parseInt(txtSeriecadNovo.getText()));

             
        n = GerNovo.getGerNovo().atualizaNovoCod(n);
        
        if(n != null){
            
            
            txtMarcacadNovo.setText(n.getMarca());
            JOptionPane.showMessageDialog(
                    null,
                    "Verifique os dados",
                    "Atualização do Carro Novo pelo número de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                   JOptionPane.showMessageDialog(
                    null,
                    "Não existe um Carro Novo com este número de serie",
                    "Alteração do Carro Novo pelo número de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
     
     
       public void consNovoSerie(){
        n = new Novo();
        n.setSerie(Integer.parseInt(txtSeriecadNovo.getText()));
          
        
        n = GerNovo.getGerNovo().consNovoCod(n);
        
        if(n != null){
            
    
           
           txtAnocadNovo.setText(Integer.toString(n.getAno()));  
           txtMarcacadNovo.setText(n.getMarca());        
           txtValorcadNovo.setText(Double.toString(n.getValor()));
           txtModelocadNovo.setText(n.getModelo());
           txtParcelascadNovo.setText(Integer.toString(n.getNumeroParcelas()));
           txtEntradacadNovo.setText(Double.toString(n.getValorEntrada()));
            
            JOptionPane.showMessageDialog(
                    null,
                    "Verifique os dados",
                    "Consulta Carro novo pelo numero de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                   JOptionPane.showMessageDialog(
                    null,
                    "Não existe Carro novo com este numero de serie",
                    "Consulta Carro novo pelo numero de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
       
       public void excNovoSerie(){
           
        n = new Novo();
        n.setSerie(Integer.parseInt(txtSeriecadNovo.getText()));
        
        n = GerNovo.getGerNovo().removeNovoCod(n);
        
        if(n == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Carro novo excluído com sucesso",
                    "Remoção de Carro Novo pelo numero de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                JOptionPane.showMessageDialog(
                    null,
                    "Não existe Carro Novo com este numero de serie",
                    "Remoção de Carro Novo pelo numero de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
            
    }
       
    public void limpar(){
        
        txtAnocadNovo.setText("");
        txtSeriecadNovo.setText("");
        txtValorcadNovo.setText("");
        txtModelocadNovo.setText("");
        txtMarcacadNovo.setText("");
        txtParcelascadNovo.setText("");
        txtEntradacadNovo.setText("");
        
        txtAnocadNovo.requestFocus();
        
    }
    public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    public void listTab(){
      DefaultTableModel modelo = (DefaultTableModel)tabNovo.getModel();
      int posLin = 0;
      modelo.setRowCount(posLin);
      
      for(Novo n : GerNovo.getGerNovo().getbdNovo()){
          modelo.insertRow(posLin, new Object[]{n.getAno(),n.getSerie(), n.getValor(), n.getModelo(), n.getMarca(), n.getNumeroParcelas(), n.getValorEntrada()});
          posLin++;
      }
   }
   
   public void selectTab(){
       String valLin = "";
       int posLin = tabNovo.getSelectedRow();
       
       for(int coluna = 0; coluna < tabNovo.getColumnCount();coluna++){
           valLin += tabNovo.getModel().getValueAt(posLin, coluna).toString();
           
           if(coluna+1 < tabNovo.getColumnCount()){
               valLin+=" - ";
           }
       }
       JOptionPane.showMessageDialog(
               null,
               "O carro novo selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    public void carregarCombNovo(){
        comboNovo.removeAllItems();
        comboNovo.addItem("Escolha um Carro: ");
        
        for(Novo n : GerNovo.getGerNovo().getbdNovo()){
            comboNovo.addItem(" Ano: "+n.getAno()+ " - Serie: "+n.getSerie() + " - Valor: "+n.getValor() + " - Modelo: "+n.getModelo() + " - Marca: "+n.getMarca() + " - NParcelas: "+n.getNumeroParcelas() + " - Valor Entrada: "+n.getValorEntrada());
        }
    }
    
    public void selectComboNovo(){
        //String valLin = "";
        if(comboNovo.getSelectedIndex()>=1){
            String valLin = comboNovo.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
                null,
                "Carro novo escolhido: \n"+valLin,
                "Seleção de Carro novo",
                JOptionPane.INFORMATION_MESSAGE                        
            );
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneNovo;
    private javax.swing.JButton btnAlterarcadNovo;
    private javax.swing.JButton btnCadastrarcadNovo;
    private javax.swing.JButton btnConsultarcadNovo;
    private javax.swing.JButton btnLimparcadNovo;
    private javax.swing.JButton btnRemovercadNovo;
    private javax.swing.JButton btnSaircadNovo;
    private javax.swing.JComboBox<String> comboNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNparcelas;
    private javax.swing.JLabel lblNserie;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblvalorEntrada;
    private javax.swing.JTable tabNovo;
    private javax.swing.JTextField txtAnocadNovo;
    private javax.swing.JTextField txtEntradacadNovo;
    private javax.swing.JTextField txtMarcacadNovo;
    private javax.swing.JTextField txtModelocadNovo;
    private javax.swing.JTextField txtParcelascadNovo;
    private javax.swing.JTextField txtSeriecadNovo;
    private javax.swing.JTextField txtValorcadNovo;
    // End of variables declaration//GEN-END:variables
}
