package com.mycompany.projetocarro;
//Matheus Duarte 2417820
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheuws Duarte
 */
public class cadSemiNovo extends javax.swing.JFrame {

    private SemiNovo s = new SemiNovo();
    private static cadSemiNovo cadastroSemiNovo;
    
    private cadSemiNovo() {
        initComponents();
    }
    
    public static cadSemiNovo getcadSemiNovo(){
        
        if(cadastroSemiNovo == null){
            
            
            cadastroSemiNovo = new cadSemiNovo();
        }
        
        return cadastroSemiNovo;
    }
    
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblNserie = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblQm = new javax.swing.JLabel();
        lblGarantia = new javax.swing.JLabel();
        txtAnocadSemiNovo = new javax.swing.JTextField();
        txtSeriecadSemiNovo = new javax.swing.JTextField();
        txtValorcadSemiNovo = new javax.swing.JTextField();
        txtModelocadSemiNovo = new javax.swing.JTextField();
        txtMarcacadSemiNovo = new javax.swing.JTextField();
        txtQmcadSemiNovo = new javax.swing.JTextField();
        txtGarantiacadSemiNovo = new javax.swing.JTextField();
        btnCadastrarcadSemiNovo = new javax.swing.JButton();
        btnConsultarcadSemiNovo = new javax.swing.JButton();
        btnAlterarcadSemiNovo = new javax.swing.JButton();
        btnRemovercadSemiNovo = new javax.swing.JButton();
        btnLimparcadSemiNovo = new javax.swing.JButton();
        btnSaircadSemiNovo = new javax.swing.JButton();
        ScrollPaneSemiNovo = new javax.swing.JScrollPane();
        tabSemiNovo = new javax.swing.JTable();
        comboSemiNovo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setText("CADASTRO CARRO SEMI-NOVO");

        lblAno.setText("Ano");

        lblNserie.setText("Número de Serie");

        lblValor.setText("Valor");

        lblModelo.setText("Modelo");

        lblMarca.setText("Marca");

        lblQm.setText("Quilometros rodados");

        lblGarantia.setText("Garantia");

        txtAnocadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnocadSemiNovoActionPerformed(evt);
            }
        });

        txtValorcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorcadSemiNovoActionPerformed(evt);
            }
        });

        txtModelocadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelocadSemiNovoActionPerformed(evt);
            }
        });

        txtMarcacadSemiNovo.setToolTipText("");
        txtMarcacadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcacadSemiNovoActionPerformed(evt);
            }
        });

        txtQmcadSemiNovo.setToolTipText("");
        txtQmcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQmcadSemiNovoActionPerformed(evt);
            }
        });

        txtGarantiacadSemiNovo.setToolTipText("");
        txtGarantiacadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarantiacadSemiNovoActionPerformed(evt);
            }
        });

        btnCadastrarcadSemiNovo.setText("Cadastrar");
        btnCadastrarcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarcadSemiNovoActionPerformed(evt);
            }
        });

        btnConsultarcadSemiNovo.setText("Consultar");
        btnConsultarcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarcadSemiNovoActionPerformed(evt);
            }
        });

        btnAlterarcadSemiNovo.setText("Alterar");
        btnAlterarcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarcadSemiNovoActionPerformed(evt);
            }
        });

        btnRemovercadSemiNovo.setText("Remover");
        btnRemovercadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovercadSemiNovoActionPerformed(evt);
            }
        });

        btnLimparcadSemiNovo.setText("Limpar");
        btnLimparcadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparcadSemiNovoActionPerformed(evt);
            }
        });

        btnSaircadSemiNovo.setText("Sair");
        btnSaircadSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaircadSemiNovoActionPerformed(evt);
            }
        });

        tabSemiNovo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "Qm", "Garantia"
            }
        ));
        tabSemiNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSemiNovoMouseClicked(evt);
            }
        });
        ScrollPaneSemiNovo.setViewportView(tabSemiNovo);

        comboSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemiNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ScrollPaneSemiNovo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(btnLimparcadSemiNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btnSaircadSemiNovo)
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQm)
                                            .addComponent(txtQmcadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGarantiacadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGarantia)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCadastrarcadSemiNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnConsultarcadSemiNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAlterarcadSemiNovo)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnRemovercadSemiNovo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModelocadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblModelo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMarca)
                                            .addComponent(txtMarcacadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAnocadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSeriecadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNserie))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblValor)
                                            .addComponent(txtValorcadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(lblTitulo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNserie)
                    .addComponent(lblAno)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeriecadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnocadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorcadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelocadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcacadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQm)
                    .addComponent(lblGarantia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQmcadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGarantiacadSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarcadSemiNovo)
                    .addComponent(btnConsultarcadSemiNovo)
                    .addComponent(btnAlterarcadSemiNovo)
                    .addComponent(btnRemovercadSemiNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPaneSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaircadSemiNovo)
                            .addComponent(btnLimparcadSemiNovo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnocadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnocadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnocadSemiNovoActionPerformed

    private void txtValorcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorcadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorcadSemiNovoActionPerformed

    private void txtModelocadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelocadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelocadSemiNovoActionPerformed

    private void txtMarcacadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcacadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcacadSemiNovoActionPerformed

    private void txtQmcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQmcadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQmcadSemiNovoActionPerformed

    private void txtGarantiacadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarantiacadSemiNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiacadSemiNovoActionPerformed

    private void tabSemiNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSemiNovoMouseClicked
        selectTab();
    }//GEN-LAST:event_tabSemiNovoMouseClicked

    private void comboSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemiNovoActionPerformed
        selectComboSemiNovo();
    }//GEN-LAST:event_comboSemiNovoActionPerformed

    private void btnCadastrarcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarcadSemiNovoActionPerformed
       cadastrar();
       listTab();
       carregarCombSemiNovo();
    }//GEN-LAST:event_btnCadastrarcadSemiNovoActionPerformed

    private void btnConsultarcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarcadSemiNovoActionPerformed
        consSemiNovoSerie();
    }//GEN-LAST:event_btnConsultarcadSemiNovoActionPerformed

    private void btnAlterarcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarcadSemiNovoActionPerformed
        altSemiNovoSerie();
        listTab();
        carregarCombSemiNovo();
    }//GEN-LAST:event_btnAlterarcadSemiNovoActionPerformed

    private void btnRemovercadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovercadSemiNovoActionPerformed
        excSemiNovoSerie();
        listTab();
        carregarCombSemiNovo();  
    }//GEN-LAST:event_btnRemovercadSemiNovoActionPerformed

    private void btnLimparcadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparcadSemiNovoActionPerformed
        limpar();
    }//GEN-LAST:event_btnLimparcadSemiNovoActionPerformed

    private void btnSaircadSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaircadSemiNovoActionPerformed
       sair();
    }//GEN-LAST:event_btnSaircadSemiNovoActionPerformed

    public void cadastrar(){
        s = new SemiNovo();
        
        try{    
            s.setAno(Integer.parseInt(txtAnocadSemiNovo.getText()));
            s.setSerie(Integer.parseInt(txtSeriecadSemiNovo.getText()));
            s.setValor(Double.parseDouble(txtValorcadSemiNovo.getText()));
            s.setModelo(txtModelocadSemiNovo.getText());
            s.setMarca(txtMarcacadSemiNovo.getText());
            s.setQm(Integer.parseInt(txtQmcadSemiNovo.getText()));
            s.setGarantia(txtGarantiacadSemiNovo.getText());
        
        s = GerSemiNovo.getGerSemiNovo().cadSemiNovo(s);
        
        if(s != null){
            JOptionPane.showMessageDialog(
                    null,
                    " Carro seminovo cadastrado com sucesso ",
                    "Cadastro Carro SemiNovo",
                    JOptionPane.PLAIN_MESSAGE
                );
            limpar();
        }
        else{
                    JOptionPane.showMessageDialog(
                    null,
                    "Já existe um Carro com esse número de Serie.",
                    "Cadastro Carro SemiNovo",
                    JOptionPane.ERROR_MESSAGE
                );
        }
    }
        catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(
                    null,
                    "O número de serie deve ser um int",
                    "Erro de preenchimento",
                    JOptionPane.ERROR_MESSAGE
                );
         }   
    }
     
     public void altSemiNovoSerie(){
        s = new SemiNovo();
        s.setSerie(Integer.parseInt(txtSeriecadSemiNovo.getText()));

             
        s = GerSemiNovo.getGerSemiNovo().atualizaSemiNovoCod(s);
        
        if(s != null){
            
            
            txtMarcacadSemiNovo.setText(s.getMarca());
            JOptionPane.showMessageDialog(
                    null,
                    " Verifique os dados ",
                    "Atualização do Carro SemiNovo pelo número de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                   JOptionPane.showMessageDialog(
                    null,
                    "Não existe um Carro SemiNovo com este número de serie",
                    "Alteração do Carro SemiNovo pelo número de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
     
     
       public void consSemiNovoSerie(){
        s = new SemiNovo();
        s.setSerie(Integer.parseInt(txtSeriecadSemiNovo.getText())); 
        
        s = GerSemiNovo.getGerSemiNovo().consSemiNovoCod(s);
        
        if(s != null){
            
    
             txtQmcadSemiNovo.setText(Integer.toString(s.getQm()));  
           txtAnocadSemiNovo.setText(Integer.toString(s.getAno()));  
           txtMarcacadSemiNovo.setText(s.getMarca());        
           txtValorcadSemiNovo.setText(Double.toString(s.getValor()));
           txtModelocadSemiNovo.setText(s.getModelo());
           txtGarantiacadSemiNovo.setText(s.getGarantia());
  
   
            
            JOptionPane.showMessageDialog(
                    null,
                    " Verifique os dados ",
                    "Consulta Carro seminovo pelo numero de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                   JOptionPane.showMessageDialog(
                    null,
                    "Não existe Carro seminovo com este numero de serie",
                    "Consulta Carro seminovo pelo numero de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
       
       public void excSemiNovoSerie(){
           
        s = new SemiNovo();
        s.setSerie(Integer.parseInt(txtSeriecadSemiNovo.getText()));
        
        s = GerSemiNovo.getGerSemiNovo().removeSemiNovoCod(s);
        
        if(s == null){
            JOptionPane.showMessageDialog(
                    null,
                    " Carro seminovo excluído com sucesso",
                    "Remoção de Carro SemiNovo pelo numero de serie",
                    JOptionPane.PLAIN_MESSAGE
            );
        }
        else{
                JOptionPane.showMessageDialog(
                    null,
                    "Não existe Carro SemiNovo com este numero de serie",
                    "Remoção de Carro SemiNovo pelo numero de serie",
                    JOptionPane.ERROR_MESSAGE
            );
        }
            
    }
       
    public void limpar(){
        
        txtAnocadSemiNovo.setText("");
        txtSeriecadSemiNovo.setText("");
        txtValorcadSemiNovo.setText("");
        txtModelocadSemiNovo.setText("");
        txtMarcacadSemiNovo.setText("");
        txtQmcadSemiNovo.setText("");
        txtGarantiacadSemiNovo.setText("");
        
        txtAnocadSemiNovo.requestFocus();
        
    }
    public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    public void listTab(){
      DefaultTableModel modelo = (DefaultTableModel)tabSemiNovo.getModel();
      int posLin = 0;
      modelo.setRowCount(posLin);
      
      for(SemiNovo s : GerSemiNovo.getGerSemiNovo().getbdSemiNovo()){
          modelo.insertRow(posLin, new Object[]{s.getAno(),s.getSerie(), s.getValor(), s.getModelo(), s.getMarca(), s.getQm(), s.getGarantia()});
          posLin++;
      }
   }
   
   public void selectTab(){
       String valLin = "";
       int posLin = tabSemiNovo.getSelectedRow();
       
       for(int coluna = 0; coluna < tabSemiNovo.getColumnCount();coluna++){
           valLin += tabSemiNovo.getModel().getValueAt(posLin, coluna).toString();
           
           if(coluna+1 < tabSemiNovo.getColumnCount()){
               valLin+=" - ";
           }
       }
       JOptionPane.showMessageDialog(
               null,
               "O carro seminovo selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    public void carregarCombSemiNovo(){
        comboSemiNovo.removeAllItems();
        comboSemiNovo.addItem("Escolha um Carro: ");
        
        for(SemiNovo s : GerSemiNovo.getGerSemiNovo().getbdSemiNovo()){
            comboSemiNovo.addItem(" Ano: "+s.getAno()+ " - Serie: "+s.getSerie() + " - Valor: "+s.getValor() + " - Modelo: "+s.getModelo() + " - Marca: "+s.getMarca() + " - Qm: "+s.getQm() + " - Garantia: "+ s.getGarantia());
        }
    }
    
    public void selectComboSemiNovo(){
        //String valLin = "";
        if(comboSemiNovo.getSelectedIndex()>=1){
            String valLin = comboSemiNovo.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
                null,
                "Carro seminovo escolhido: \n"+valLin,
                "Seleção de Carro seminovo",
                JOptionPane.INFORMATION_MESSAGE                        
            );
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadSemiNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadSemiNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadSemiNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadSemiNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadSemiNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneSemiNovo;
    private javax.swing.JButton btnAlterarcadSemiNovo;
    private javax.swing.JButton btnCadastrarcadSemiNovo;
    private javax.swing.JButton btnConsultarcadSemiNovo;
    private javax.swing.JButton btnLimparcadSemiNovo;
    private javax.swing.JButton btnRemovercadSemiNovo;
    private javax.swing.JButton btnSaircadSemiNovo;
    private javax.swing.JComboBox<String> comboSemiNovo;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNserie;
    private javax.swing.JLabel lblQm;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tabSemiNovo;
    private javax.swing.JTextField txtAnocadSemiNovo;
    private javax.swing.JTextField txtGarantiacadSemiNovo;
    private javax.swing.JTextField txtMarcacadSemiNovo;
    private javax.swing.JTextField txtModelocadSemiNovo;
    private javax.swing.JTextField txtQmcadSemiNovo;
    private javax.swing.JTextField txtSeriecadSemiNovo;
    private javax.swing.JTextField txtValorcadSemiNovo;
    // End of variables declaration//GEN-END:variables
}
