package com.mycompany.projetocarro;
//Matheus Duarte 2417820

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheuws Duarte
 */
public class PrincipalMenu extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalMenu
     */
    public PrincipalMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuCarroNovo = new javax.swing.JMenuItem();
        jMenuCarroSemiNovo = new javax.swing.JMenuItem();
        jMenuCarroUsado = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPrincipal.setText("Menu");
        jMenuPrincipal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jMenuPrincipalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jMenuCadastrar.setText("Cadastrar");

        jMenuCarroNovo.setText("Carro Novo");
        jMenuCarroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarroNovoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCarroNovo);

        jMenuCarroSemiNovo.setText("Carro SemiNovo");
        jMenuCarroSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarroSemiNovoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCarroSemiNovo);

        jMenuCarroUsado.setText("Carro Usado");
        jMenuCarroUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarroUsadoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuCarroUsado);

        jMenuPrincipal.add(jMenuCadastrar);

        jMenuRelatorio.setText("Relatorio");
        jMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRelatorioActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuRelatorio);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuSair);

        jMenuBarPrincipal.add(jMenuPrincipal);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPrincipalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jMenuPrincipalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPrincipalAncestorAdded

    private void jMenuCarroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarroNovoActionPerformed
        abrirCadNovo();
    }//GEN-LAST:event_jMenuCarroNovoActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        sair();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCarroSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarroSemiNovoActionPerformed
        abrirCadSemiNovo();
    }//GEN-LAST:event_jMenuCarroSemiNovoActionPerformed

    private void jMenuCarroUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarroUsadoActionPerformed
        abrirCadUsado();
    }//GEN-LAST:event_jMenuCarroUsadoActionPerformed

    private void jMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRelatorioActionPerformed
        abrirRelatorio();
    }//GEN-LAST:event_jMenuRelatorioActionPerformed
    
    public void abrirCadNovo(){
        //new CadPes().setVisible(true);
        cadNovo.getcadNovo().setVisible(true);
        
    }
    
    public void abrirCadSemiNovo(){
        
        cadSemiNovo.getcadSemiNovo().setVisible(true);
        
    }
    
    public void abrirCadUsado(){
    
        cadUsado.getcadUsado().setVisible(true);
        
    }
    
    public void abrirRelatorio(){
        
        Relatorio.getRelatorio().setVisible(true);
        
    }
    
    public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCarroNovo;
    private javax.swing.JMenuItem jMenuCarroSemiNovo;
    private javax.swing.JMenuItem jMenuCarroUsado;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenuItem jMenuRelatorio;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    // End of variables declaration//GEN-END:variables
}
