package com.mycompany.projetocarro;
//Matheus Duarte 2417820
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheuws Duarte
 */
public class Relatorio extends javax.swing.JFrame {

    private Novo n = new Novo();
    private SemiNovo s = new SemiNovo();
    private  Usado u = new Usado();
    private static Relatorio relatorioUnico;
    
    private Relatorio() {
        initComponents();
      
    
    }
    
    public static Relatorio getRelatorio(){
        
        if(relatorioUnico == null){
            relatorioUnico = new Relatorio();
        }
        
        return relatorioUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneUsado = new javax.swing.JScrollPane();
        tabUsado = new javax.swing.JTable();
        ScrollPaneNovo = new javax.swing.JScrollPane();
        tabNovo = new javax.swing.JTable();
        ScrollPaneSemiNovo = new javax.swing.JScrollPane();
        tabSemiNovo = new javax.swing.JTable();
        comboNovo = new javax.swing.JComboBox<>();
        comboSemiNovo = new javax.swing.JComboBox<>();
        comboUsado = new javax.swing.JComboBox<>();
        btnSaircadNovo = new javax.swing.JButton();
        ScrollPaneUsado2 = new javax.swing.JScrollPane();
        tabUsado2 = new javax.swing.JTable();

        tabUsado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "Tempo Uso", "Valor Manutencao"
            }
        ));
        tabUsado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUsadoMouseClicked(evt);
            }
        });
        ScrollPaneUsado.setViewportView(tabUsado);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabNovo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "N° Parcelas", "Valor Entrada"
            }
        ));
        tabNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNovoMouseClicked(evt);
            }
        });
        ScrollPaneNovo.setViewportView(tabNovo);

        tabSemiNovo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "Qm", "Garantia"
            }
        ));
        tabSemiNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabSemiNovoMouseClicked(evt);
            }
        });
        ScrollPaneSemiNovo.setViewportView(tabSemiNovo);

        comboNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNovoActionPerformed(evt);
            }
        });

        comboSemiNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemiNovoActionPerformed(evt);
            }
        });

        comboUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUsadoActionPerformed(evt);
            }
        });

        btnSaircadNovo.setText("Sair");
        btnSaircadNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaircadNovoActionPerformed(evt);
            }
        });

        tabUsado2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ano", "Serie", "Valor", "Modelo", "Marca", "Tempo Uso", "Valor Manutencao"
            }
        ));
        tabUsado2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabUsado2MouseClicked(evt);
            }
        });
        ScrollPaneUsado2.setViewportView(tabUsado2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneUsado2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ScrollPaneNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                        .addComponent(ScrollPaneSemiNovo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboUsado, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaircadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollPaneSemiNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboUsado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaircadNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollPaneUsado2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNovoMouseClicked
        selectTabNovo();
    }//GEN-LAST:event_tabNovoMouseClicked

    private void tabSemiNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabSemiNovoMouseClicked
        selectTabSemiNovo();
    }//GEN-LAST:event_tabSemiNovoMouseClicked

    private void tabUsadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsadoMouseClicked
        selectTabUsado();
    }//GEN-LAST:event_tabUsadoMouseClicked

    private void comboNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNovoActionPerformed
        selectComboNovo();
    }//GEN-LAST:event_comboNovoActionPerformed

    private void comboSemiNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemiNovoActionPerformed
        selectComboSemiNovo();
    }//GEN-LAST:event_comboSemiNovoActionPerformed

    private void comboUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUsadoActionPerformed
        selectComboUsado();
    }//GEN-LAST:event_comboUsadoActionPerformed

    private void btnSaircadNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaircadNovoActionPerformed
        sair();
    }//GEN-LAST:event_btnSaircadNovoActionPerformed

    private void tabUsado2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabUsado2MouseClicked
        selectTabUsado();
    }//GEN-LAST:event_tabUsado2MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTabNovo();
        listTabSemiNovo();
        listTabUsado();
        carregarCombNovo();
        carregarCombSemiNovo();
        carregarCombUsado();
    }//GEN-LAST:event_formWindowActivated
    
      public void sair(){
            int respSair = JOptionPane.showConfirmDialog(
                        null,
                        "Deseja realmente sair?",
                        "Saida",
                        JOptionPane.YES_NO_OPTION
                );
        if(respSair == 0){
            //System.exit(0);
            dispose();
        }
    }
    
    //Tabela Novo
    public void listTabNovo(){
      DefaultTableModel modelo = (DefaultTableModel)tabNovo.getModel();
      int posLin = 0;
      modelo.setRowCount(posLin);
      
      for(Novo n : GerNovo.getGerNovo().getbdNovo()){
          modelo.insertRow(posLin, new Object[]{n.getAno(),n.getSerie(), n.getValor(), n.getModelo(), n.getMarca(), n.getNumeroParcelas(), n.getValorEntrada()});
          posLin++;
      }
   }
    
    
    public void selectTabNovo(){
       String valLin = "";
       int posLin = tabNovo.getSelectedRow();
       
       for(int coluna = 0; coluna < tabNovo.getColumnCount();coluna++){
           valLin += tabNovo.getModel().getValueAt(posLin, coluna).toString();
           
           if(coluna+1 < tabNovo.getColumnCount()){
               valLin+=" - ";
           }
       }
       JOptionPane.showMessageDialog(
               null,
               "O carro novo selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    
     public void carregarCombNovo(){
        comboNovo.removeAllItems();
        comboNovo.addItem("Escolha um Carro: ");
        
        for(Novo n : GerNovo.getGerNovo().getbdNovo()){
            comboNovo.addItem(" Ano: "+n.getAno()+ " - Serie: "+n.getSerie() + " - Valor: "+n.getValor() + " - Modelo: "+n.getModelo() + " - Marca: "+n.getMarca() + " - NParcelas: "+n.getNumeroParcelas() + " - Valor Entrada: "+n.getValorEntrada());
        }
    }
    
    public void selectComboNovo(){
        //String valLin = "";
        if(comboNovo.getSelectedIndex()>=1){
            String valLin = comboNovo.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
                null,
                "Carro novo escolhido: \n"+valLin,
                "Seleção de Carro novo",
                JOptionPane.INFORMATION_MESSAGE                        
            );
        }
    }
    //Novo
    
    //SemiNovo
     public void listTabSemiNovo(){
      DefaultTableModel modelo = (DefaultTableModel)tabSemiNovo.getModel();
      int posLin = 0;
      modelo.setRowCount(posLin);
      
      for(SemiNovo s : GerSemiNovo.getGerSemiNovo().getbdSemiNovo()){
          modelo.insertRow(posLin, new Object[]{s.getAno(),s.getSerie(), s.getValor(), s.getModelo(), s.getMarca(), s.getQm(), s.getGarantia()});
          posLin++;
      }
   }
   
   public void selectTabSemiNovo(){
       String valLin = "";
       int posLin = tabSemiNovo.getSelectedRow();
       
       for(int coluna = 0; coluna < tabSemiNovo.getColumnCount();coluna++){
           valLin += tabSemiNovo.getModel().getValueAt(posLin, coluna).toString();
           
           if(coluna+1 < tabSemiNovo.getColumnCount()){
               valLin+=" - ";
           }
       }
       JOptionPane.showMessageDialog(
               null,
               "O carro seminovo selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    public void carregarCombSemiNovo(){
        comboSemiNovo.removeAllItems();
        comboSemiNovo.addItem("Escolha um Carro: ");
        
        for(SemiNovo s : GerSemiNovo.getGerSemiNovo().getbdSemiNovo()){
            comboSemiNovo.addItem(" Ano: "+s.getAno()+ " - Serie: "+s.getSerie() + " - Valor: "+s.getValor() + " - Modelo: "+s.getModelo() + " - Marca: "+s.getMarca() + " - Qm: "+s.getQm() + " - Garantia: "+ s.getGarantia());
        }
    }
    
    public void selectComboSemiNovo(){
        //String valLin = "";
        if(comboSemiNovo.getSelectedIndex()>=1){
            String valLin = comboSemiNovo.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
                null,
                "Carro seminovo escolhido: \n"+valLin,
                "Seleção de Carro seminovo",
                JOptionPane.INFORMATION_MESSAGE                        
            );
        }
    } 
    
    //SemiNovo
    
    
    //Usado
    
     public void listTabUsado(){
      DefaultTableModel modelo = (DefaultTableModel)tabUsado2.getModel();
      int posLin = 0;
      modelo.setRowCount(posLin);
      
      for(Usado u : GerUsado.getGerUsado().getbdUsado()){
          modelo.insertRow(posLin, new Object[]{u.getAno(),u.getSerie(), u.getValor(), u.getModelo(), u.getMarca(), u.getTempoUso(), u.getValorManutencao()});
          posLin++;
      }
   }
   
   public void selectTabUsado(){
       String valLin = "";
       int posLin = tabUsado2.getSelectedRow();
       
       for(int coluna = 0; coluna < tabUsado2.getColumnCount();coluna++){
           valLin += tabUsado2.getModel().getValueAt(posLin, coluna).toString();
           
           if(coluna+1 < tabUsado2.getColumnCount()){
               valLin+=" - ";
           }
       }
       JOptionPane.showMessageDialog(
               null,
               "O carro usado selecionado foi: \n"+valLin,
               "Resultado da seleção",
               JOptionPane.INFORMATION_MESSAGE
       );
    }
    public void carregarCombUsado(){
        comboUsado.removeAllItems();
        comboUsado.addItem("Escolha um Carro: ");
        
        for(Usado u : GerUsado.getGerUsado().getbdUsado()){
            comboUsado.addItem(" Ano: "+u.getAno()+ " - Serie: "+u.getSerie() + " - Valor: "+u.getValor() + " - Modelo: "+u.getModelo() + " - Marca: "+u.getMarca() + " - Tempo uso: "+u.getTempoUso()+ " - Valor Manutencao: "+ u.getValorManutencao());
        }
    }
    
    public void selectComboUsado(){
        //String valLin = "";
        if(comboUsado.getSelectedIndex()>=1){
            String valLin = comboUsado.getSelectedItem().toString();
        JOptionPane.showMessageDialog(
                null,
                "Carro usado escolhido: \n"+valLin,
                "Seleção de Carro usado",
                JOptionPane.INFORMATION_MESSAGE                        
            );
        }
    }
    
    
    //Usado
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneNovo;
    private javax.swing.JScrollPane ScrollPaneSemiNovo;
    private javax.swing.JScrollPane ScrollPaneUsado;
    private javax.swing.JScrollPane ScrollPaneUsado2;
    private javax.swing.JButton btnSaircadNovo;
    private javax.swing.JComboBox<String> comboNovo;
    private javax.swing.JComboBox<String> comboSemiNovo;
    private javax.swing.JComboBox<String> comboUsado;
    private javax.swing.JTable tabNovo;
    private javax.swing.JTable tabSemiNovo;
    private javax.swing.JTable tabUsado;
    private javax.swing.JTable tabUsado2;
    // End of variables declaration//GEN-END:variables
}
